### ISSUE TITLE
Panels are drawn but no information is shown until cookies are cleared.

### ISSUE THREAD

**Issue by SX86** [ronggang/transmission-web-control#113]
I installed Transmission WEB Control yesterday, and noticed that when I return to the page on the next day, it refreshes it automatically with empty panels. All the controls are there, but do not do anything when clicked on, until I clear Chrome's cookies for the website.

It seems to happen after I click to show Folders, and expand them, then refresh.

![screenshot 2017-11-12 at 08 44 56](https://user-images.githubusercontent.com/17429368/32699569-cacb246e-c785-11e7-9b02-95cc67ce4cde.png)

**Comment by ronggang** [comment]
@SX86 Please install latest release. You can try this install script https://github.com/ronggang/transmission-web-control/blob/master/release/install-tr-control.sh

**Comment by SX86** [comment]
@ronggang 
I had installed using the "easy install" script. It had install version 1.1 Beta.
I am now running 1.4. Will report back if problem is unresolved.

Thank you!

**Comment by vodek3** [comment]
This is due to the fact that's in the "script" folder and its sub-folders are located "cookies*.js" files.
I had the same issue with mine QNAP TS-231 and Media Player Measy x5 when I installed manually Transmission Web Control without use bash-script.

Just delete "cookies*.js"! ;-)

By the way, transfer-control-full.tar.gz contains two files (cookies.js and cookies.min.js) along the following paths:
Web\web-management\script\cookies.js
Web\web-management\script\cookies.min.js
