### ISSUE TITLE
What "Automatically matches data directory" does?

### ISSUE THREAD

**Issue by auanasgheps** [ronggang/transmission-web-control#220]
* Transmssion version: 2.93
* Tr Web Control version: 1.5.1
* Problem description: Automatically matches data directory

Hello, I can't understand what **Automatically matches data directory** does. I understand the creator is not a native english speaker... but does not make any sense to me. I am re-working the Italian translation and I am trying to give a meaning to this feature.

Also can you confirm what this message means? It is shown on _Replace Trackers_ screen:
`"This function will find <b>all torrents</b> Tracker." `
Does replace old tracker with the new tracker in every matching torrent and reannounce? That's the only sense I've found.
Thank you

**Comment by Monter** [comment]
I have not used this option yet, but it looks like a mechanism for matching different target folders (entered in the dictionary) on the basis of names.
If I'm wrong, please correct me.

**Comment by auanasgheps** [comment]
> matching different target folders (entered in the dictionary) on the basis of names.

Not sure if I understood. Means that if the torrent contains a specific keyword I can automatically set a taget folder?

Oh yes... I almost forgot folder dictionary! What is that? How should be used? It's just a directory for download folders?

**Comment by ronggang** [comment]
@auanasgheps About "Automatically matches data directory", This feature is usually used for PT.
Probably mean: match the new seed content according to the directory dictionary and automatically verify.

**Comment by auanasgheps** [comment]
P looks like as a plugin to add torrents to Transmission straight from the browser, but looks like there is much more. Because I've never used PT (it's in Chinese) I don't know what this plugin can do.

What do you mean with "match the new seed content"?

**Comment by ronggang** [comment]
@auanasgheps PT = Private Tracker.
Sorry for my english, :) i'm used google translate. 
For Example
I need add some torrents, I know they have been downloaded, but I don't know exactly which directory to save, so I need a directory dictionary to use for automatic matching. So I've defined a dictionary that contains 100 directories. 
* This is my directory dictionary
![tim 20180420083455](https://user-images.githubusercontent.com/8065899/39025037-2fe1f9a4-4477-11e8-86e4-bd48bc71058d.png)
* I add some torrents
![tim 20180420083009](https://user-images.githubusercontent.com/8065899/39025056-6050b904-4477-11e8-9a9d-073d4ba532ea.png)
1. I chose a default directory
2. Add torrent url
3. Do not auto start.

* Now, There are some torrents showing progress of 0 because they didn't find the real data directory
![tim 20180420083217](https://user-images.githubusercontent.com/8065899/39025157-f4c02d9a-4477-11e8-828e-f66930dffe12.png)


* I select all the unfinished torrents (7 torrents) and use this feature.
![tim 20180420083426](https://user-images.githubusercontent.com/8065899/39025271-9ccc2bf6-4478-11e8-82ba-f26b2f4d5d7e.png)

* Let it begin to work and wait for execution to complete
![tim 20180420083601](https://user-images.githubusercontent.com/8065899/39025332-e3af1f74-4478-11e8-874f-eb80ad999a1a.png)

* Now, I got the following results, 2 torrents matched.
![tim 20180420090605](https://user-images.githubusercontent.com/8065899/39025532-3bed97d2-447a-11e8-8496-09da0d88ca29.png)

**Comment by Monter** [comment]
I do not use this but a tutorial on this topic could appear in the project Wiki.

**Comment by auanasgheps** [comment]
@ronggang thanks for the explanation. 

Yes this could be used as tutorial!

**Comment by ronggang** [comment]
Okay, I'll update it to Wiki

**Comment by auanasgheps** [comment]
Closing for cleanup.
